### PR TITLE
Updated path in module-postlink.js for android & ios core builds in version 0.59 of RN.

### PR DESCRIPTION
**Pull request by coreyphillips**
Version 0.59 of RN breaks module-postscript.js due to the new location of the ios & android core builds. This PR updates the path to the new location, resolving the issue.

### CODE REVIEW

**Comment by jaimecbernardo** [comment]
Hi @coreyphillips , Thank you for the PR. I'll give it a try.

**Comment by jaimecbernardo** [comment]
Hi @coreyphillips , I've given it a try, and I still get: 
```
Error: Cannot find module './../../../node_modules/@react-native-community/cli/build/core/android
```
Tried it with react-native `0.59.0` and `0.59.1`.

**Comment by unmec** [comment]
The latest RN extracted cli, so we need first install it:
```
npm install --save react-native-cli
```

The latest cli has a different path, we need actually modify module-postlink.js with:
```
const android = require('./../../../node_modules/@react-native-community/cli/build/tools/android');
const ios = require('./../../../node_modules/@react-native-community/cli/build/tools/ios');
```

Then link the package, it should now work as expected.

**Comment by jaimecbernardo** [comment]
Hi @unmec ,

Thank you for the additional information.
Using your suggested path works.
Will prepare a release with it after some more testing.

**Comment by jaimecbernardo** [comment]
The location from this PR didn't work for any of my tests, so I'm closing this.
Ended up using the path suggested by @unmec and include a path to keep older react-native versions working: https://github.com/janeasystems/nodejs-mobile-react-native/commit/ba9d5d48c413550a890aeb9ec2e895db93eeb5bb

This was released in https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.3.4

Thanks @coreyphillips and @unmec for your help.
